# Generated by Django 4.2.5 on 2023-09-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
