# Generated by Django 4.2.5 on 2023-10-05 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalUsers',
            new_name='HistoricalUser',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
