# Generated by Django 4.2.5 on 2023-10-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_historicaluser_nombre_alter_user_nombre'),
        ('tallerApp', '0001_initial'),
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=30, null=True)),
                ('departamentos_asociados', models.CharField(max_length=30, null=True)),
                ('creacion_tarea', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('entregado', models.BooleanField()),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerApp.talleruser')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'TallerTask',
                'verbose_name_plural': 'TallerTasks',
            },
        ),
    ]
